
unoegohh_admin:
    resource: "@UnoegohhAdminBundle/Resources/config/routing.yml"
    prefix:   /admin


unoegohh_entities:
    resource: "@UnoegohhEntitiesBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

unoegohh_shop:
    resource: "@UnoegohhShopBundle/Resources/config/routing.yml"
    prefix:   /tmp

unoegohh_shop_temp_index_ru:
    path:     /
    defaults: { _controller: UnoegohhShopBundle:Temp:IndexRu}

unoegohh_shop_temp_index_eng:
    path:     /eng
    defaults: { _controller: UnoegohhShopBundle:Temp:IndexEng}

unoegohh_shop_temp_cart_ru:
    path:     /cart
    defaults: { _controller: UnoegohhShopBundle:Temp:CartRu}

unoegohh_shop_temp_cart_eng:
    path:     /eng/cart
    defaults: { _controller: UnoegohhShopBundle:Temp:CartEng}
