unoegohh_admin_homepage:
    path:     /
    defaults: { _controller: UnoegohhAdminBundle:Default:index }

# site prefs
unoegohh_admin_site_pref:
    path:     /site_pref
    defaults: { _controller: UnoegohhAdminBundle:SitePref:index }

# contact prefs
unoegohh_admin_contact_pref:
    path:     /contact
    defaults: { _controller: UnoegohhAdminBundle:Contact:index }

# food category
unoegohh_admin_food_category:
    path:     /item_cat
    defaults: { _controller: UnoegohhAdminBundle:ItemCategory:index }

unoegohh_admin_food_category_create:
    path:     /item_cat/create
    defaults: { _controller: UnoegohhAdminBundle:ItemCategory:create }

unoegohh_admin_food_category_edit:
    path:     /item_cat/edit/{id}
    defaults: { _controller: UnoegohhAdminBundle:ItemCategory:edit }

unoegohh_admin_food_category_remove:
    path:     /item_cat/remove/{id}
    defaults: { _controller: UnoegohhAdminBundle:ItemCategory:remove }

unoegohh_admin_food_category_remove_ok:
    path:     /item_cat/remove/{id}/ok
    defaults: { _controller: UnoegohhAdminBundle:ItemCategory:removeOk }

# banners
unoegohh_admin_banners:
    path:     /banners
    defaults: { _controller: UnoegohhAdminBundle:MainBanner:index }

unoegohh_admin_banners_create:
    path:     /banners/create
    defaults: { _controller: UnoegohhAdminBundle:MainBanner:create }

unoegohh_admin_banners_edit:
    path:     /banners/edit/{id}
    defaults: { _controller: UnoegohhAdminBundle:MainBanner:edit }

unoegohh_admin_banners_remove:
    path:     /banners/remove/{id}
    defaults: { _controller: UnoegohhAdminBundle:MainBanner:remove }

unoegohh_admin_banners_remove_ok:
    path:     /banners/remove/{id}/ok
    defaults: { _controller: UnoegohhAdminBundle:MainBanner:removeOk }

# food item
unoegohh_admin_food_item:
    path:     /item
    defaults: { _controller: UnoegohhAdminBundle:Item:index }

unoegohh_admin_food_item_create:
    path:     /item/create
    defaults: { _controller: UnoegohhAdminBundle:Item:create }

unoegohh_admin_food_item_edit:
    path:     /item/edit/{id}
    defaults: { _controller: UnoegohhAdminBundle:Item:edit }

unoegohh_admin_food_item_remove:
    path:     /item/remove/{id}
    defaults: { _controller: UnoegohhAdminBundle:Item:remove }

unoegohh_admin_food_item_remove_ok:
    path:     /item/remove/{id}/ok
    defaults: { _controller: UnoegohhAdminBundle:Item:removeOk }

unoegohh_admin_photo_add:
    path:     /item/photo/add/{id}
    defaults: { _controller: UnoegohhAdminBundle:Item:imageUpload }

unoegohh_admin_photo_remove:
    path:     /item/photo/remove/{id}
    defaults: { _controller: UnoegohhAdminBundle:Item:removeImage }

# static pages

unoegohh_admin_static_page:
    path:     /static_page
    defaults: { _controller: UnoegohhAdminBundle:StaticPage:index }

unoegohh_admin_static_page_create:
    path:     /static_page/create
    defaults: { _controller: UnoegohhAdminBundle:StaticPage:create }

unoegohh_admin_static_page_edit:
    path:     /static_page/edit/{id}
    defaults: { _controller: UnoegohhAdminBundle:StaticPage:edit }

unoegohh_admin_static_page_remove:
    path:     /static_page/remove/{id}
    defaults: { _controller: UnoegohhAdminBundle:StaticPage:remove }

unoegohh_admin_static_page_remove_ok:
    path:     /static_page/remove/{id}/ok
    defaults: { _controller: UnoegohhAdminBundle:StaticPage:removeOk }

unoegohh_admin_static_page_image_upload:
    path:     /static_page/upload
    defaults: { _controller: UnoegohhAdminBundle:StaticPage:imageUpload }

#menu

unoegohh_admin_menu:
    path:     /menu
    defaults: { _controller: UnoegohhAdminBundle:MenuItem:index }

unoegohh_admin_menu_create:
    path:     /menu/create
    defaults: { _controller: UnoegohhAdminBundle:MenuItem:create }

unoegohh_admin_menu_edit:
    path:     /menu/edit/{id}
    defaults: { _controller: UnoegohhAdminBundle:MenuItem:edit }

unoegohh_admin_menu_remove:
    path:     /menu/remove/{id}
    defaults: { _controller: UnoegohhAdminBundle:MenuItem:remove }

unoegohh_admin_menu_remove_ok:
    path:     /menu/remove/{id}/ok
    defaults: { _controller: UnoegohhAdminBundle:MenuItem:removeOk }


#orders

unoegohh_admin_orders:
    path:     /orders
    defaults: { _controller: UnoegohhAdminBundle:Orders:index }

unoegohh_admin_orders_edit:
    path:     /orders/{id}
    defaults: { _controller: UnoegohhAdminBundle:Orders:edit }

